---
  - name: Copy docker daemon config
    copy:
      src: daemon.json
      dest: /etc/docker/daemon.json

  - name: Restart docker
    systemd: 
      state: restarted
      name: docker

  - name: Create the honeybee user
    user:
      name: honeybee
      groups:
       - sudo
       - docker
      state: present
      shell: /bin/bash
      system: no
      createhome: yes
      home: /home/honeybee

  - name: Creates Honeybee ssh directory
    file:
      path: /home/honeybee/.ssh
      state: directory
      owner: honeybee
      group: honeybee
      mode: 0700

  - name: Add authorized key for Honeybee
    copy:
      src: credentials/id_ed25519.pub
      dest: /home/honeybee/.ssh/authorized_keys
      owner: honeybee
      group: honeybee
      mode: 0644
